import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from '../redux/provider'
=======

import { store } from '@/redux/store';
>>>>>>> 492fe3069fa30d915b761271c537d20db9136272



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
<<<<<<< HEAD
      <Providers>
        {children}
        </Providers>
=======
      
        {children}
>>>>>>> 492fe3069fa30d915b761271c537d20db9136272
      </body>
    </html>
  );
}
